stages:    
  - build     
  - deploy

build-job:       
  stage: build
  script:
    - git pull --recurse-submodules
    - ls -R
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:     
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
