variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/

image:
  maven:3.8.1-jdk-11

stages:    
  - build     
  - deploy

build-job:       
  stage: build
  script:
    - echo "$CI_COMMIT_REF_SLUG"
    - echo "Compiling the code..."
    - mvn package
    - echo "Compile complete."

deploy-job:     
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
